# -*- coding: utf-8 -*-
"""CIS480_Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DI2kUezV-3jBmLWHTmLCOWshxAeQu7mF
"""

!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!pip install pyspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importing Datasets and Cleaning"""

median_housing = pd.read_csv('/content/median_house_value.csv', header=1)
median_housing.head()

median_housing.isna().sum()

median_housing.dropna(inplace=True)
median_housing.isna().sum()

computer_access = pd.read_csv('/content/household_computer_access.csv', header=1)
computer_access.head()

computer_access.isna().sum()

computer_access.dropna(inplace=True)
computer_access.isna().sum()

congressional_districts = pd.read_csv('/content/zipcodes_with_congressional_district.csv')
congressional_districts.head()

congressional_districts = congressional_districts.rename(columns={'ZipCode': 'zipcode'})
congressional_districts.head()

congressional_districts.isna().sum()

food_district = pd.read_csv('/content/foodDistrict.csv', header=1)
food_district.head()

food_district = food_district.rename(columns={'GeoID_Name':'District'})
food_district.head()

food_district.isna().sum()

scores = pd.read_csv('/content/proficiency.csv')
scores.head()

scores.isna().sum()

scores.dropna(inplace=True)
scores.isna().sum()

scores['SchoolID'] = scores['SchoolID'].astype(int)
scores.head()

schools = pd.read_csv('/content/PublicSchoolsList.csv')
schools.head()

schools = schools[schools['Phoenix'] == True]

schools.isna().sum()

schools = schools.rename(columns={'School Id': 'SchoolID'})
schools.info()

schools['zipcode'] = schools['Physical Address'].str.extract(r'(\d{5})(?:-\d{4})?$')
schools.head()

"""Merging Datasets"""

scores_merged = scores.merge(schools[['SchoolID','zipcode']], on='SchoolID')
scores_merged.head()

scores_merged['zipcode'] = scores_merged['zipcode'].astype(str)
congressional_districts['zipcode'] = congressional_districts['zipcode'].astype(str)

merged_housing_computer = median_housing.merge(computer_access[['GeoID_Name', 'phh_comp']], on='GeoID_Name')
merged_housing_computer.head()

merged_housing_computer = merged_housing_computer.rename(columns={'GeoID_Name': 'zipcode'})
merged_housing_computer.head()

merged_housing_computer['zipcode'] = merged_housing_computer['zipcode'].astype(str)

district_merged = congressional_districts.merge(food_district, on='District')
district_merged.head()

merged_factors = merged_housing_computer.merge(district_merged[['zipcode', 'District', 'p_fi_rate']], on='zipcode')
merged_factors.head()

merged_factors.info()

merged = scores_merged.merge(merged_factors[['zipcode', 'District', 'p_fi_rate', 'mhv', 'phh_comp']], on='zipcode')
merged.head()

merged = merged.drop(['County', 'SchoolCTDS', 'Subgroup', 'Test Level'], axis=1)
merged.head()

merged = merged.rename(columns={'FiscalYear': 'year','SchoolID': 'schoolId', 'SchoolName': 'schoolName', 'Subject': 'subject','Number Tested': 'tested','Percent Passing': 'percentPassing', 'District': 'district', 'p_fi_rate': 'foodInsecurityPercent', 'mhv': 'medianHouseValue', 'phh_comp': 'computerAccessPercentage'})
merged['year'] = merged['year'].astype(int)
merged.head()

merged.info()

"""Downloading Merged Dataset"""

from google.colab import files
merged.to_csv('merged.csv')
files.download('merged.csv')

"""Data Modeling

Food Insecurity
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

merged = merged[['percentPassing', 'foodInsecurityPercent', 'medianHouseValue', 'computerAccessPercentage']]
merged.info()

X = merged[['foodInsecurityPercent']]
y = merged['percentPassing']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

food_model = LinearRegression()
food_model.fit(X_train, y_train)

y_pred_food = food_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred_food))

print("Food Insecurity Levels Compared to Passing Percentage")
print("Coefficient:", food_model.coef_[0])
print("Intercept:", food_model.intercept_)
print("R²:", r2_score(y_test, y_pred_food))
print("RMSE:", rmse)

import matplotlib.pyplot as plt

X_sorted = np.sort(X_test.values, axis=0)
y_pred_sorted = food_model.predict(X_sorted)
plt.figure(figsize=(8,6))
plt.scatter(X_test, y_test)
plt.plot(X_sorted, y_pred_sorted)
plt.xlabel("Food Insecurity Percentage")
plt.ylabel("Percent Passing")
plt.title("Linear Regression: Food Insecurity vs Percent Passing")
plt.show()

"""Median Housing Value"""

X = merged[['medianHouseValue']]
y = merged['percentPassing']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

mhv_model = LinearRegression()
mhv_model.fit(X_train, y_train)

y_pred_mhv = mhv_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred_mhv))

print("Median Housing Value Compared to Passing Percentage")
print("Coefficient:", mhv_model.coef_[0])
print("Intercept:", mhv_model.intercept_)
print("R²:", r2_score(y_test, y_pred_food))
print("RMSE:", rmse)

X_sorted = np.sort(X_test.values, axis=0)
y_pred_sorted = mhv_model.predict(X_sorted)
plt.figure(figsize=(8,6))
plt.scatter(X_test, y_test)
plt.plot(X_sorted, y_pred_sorted)
plt.xlabel("Median Housing Value ($)")
plt.ylabel("Percent Passing")
plt.title("Linear Regression: Median Housing Value vs Percent Passing")
plt.show()

"""Computer Access Percentage"""

X = merged[['computerAccessPercentage']]
y = merged['percentPassing']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

cap_model = LinearRegression()
cap_model.fit(X_train, y_train)

y_pred_cap = cap_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred_cap))

print("Computer Access Percentage Compared to Passing Percentage")
print("Coefficient:", cap_model.coef_[0])
print("Intercept:", cap_model.intercept_)
print("R²:", r2_score(y_test, y_pred_food))
print("RMSE:", rmse)

X_sorted = np.sort(X_test.values, axis=0)
y_pred_sorted = cap_model.predict(X_sorted)
plt.figure(figsize=(8,6))
plt.scatter(X_test, y_test)
plt.plot(X_sorted, y_pred_sorted)
plt.xlabel("Computer Access Percentage")
plt.ylabel("Percent Passing")
plt.title("Linear Regression: Computer Access Percentage vs Percent Passing")
plt.show()

"""Multiple Linear Regression"""

X = merged[['medianHouseValue', 'computerAccessPercentage', 'foodInsecurityPercent']]
y = merged['percentPassing']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

mlr_model = LinearRegression()
mlr_model.fit(X_train, y_train)

y_pred = mlr_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2 = r2_score(y_test, y_pred)

print("Multiple Linear Regression")
print("Coefficient:", mlr_model.coef_)
print("Intercept:", mlr_model.intercept_)
print("R²:", r2)
print("RMSE:", rmse)

plt.figure(figsize=(10,6))
plt.scatter(y_test, y_pred)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')
plt.xlabel("Actual Percent Passing")
plt.ylabel("Predicted Percent Passing")
plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals, alpha=0.6)
plt.axhline(0, color='red', linewidth=2)

plt.xlabel("Predicted Scores")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

